name: CNTV EPG Updater

on:
  schedule:
    - cron: '0 17 * * *'  # 每天UTC 17:00（北京时间凌晨1点）
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为北京时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml pytz

    - name: Run EPG Generator
      run: |
        echo "开始生成CNTV EPG数据..."
        if ! python cntvepg.py; then
          echo "::error::CNTV EPG生成失败！检查cntvepg.py脚本"
          exit 1
        fi

    - name: Debug Files
      run: |
        if [ -s cntvepg.xml.gz ]; then
          echo "GZ 文件存在且非空"
          echo "GZ 文件大小：$(du -h cntvepg.xml.gz | cut -f1)"
          echo "文件内容前100字符："
          gzip -dc cntvepg.xml.gz | head -c 100
          echo ""
        else
          echo "::error::GZ文件为空或不存在"
          exit 1
        fi

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        if [ -s cntvepg.xml.gz ]; then
          git add cntvepg.xml.gz
          COMMIT_TIME=$(date +'%Y-%m-%d %H:%M (CST)')
          COMMIT_MSG="CNTV EPG自动更新 $COMMIT_TIME"
          git commit -m "$COMMIT_MSG"
          git pull origin main --rebase  # 拉取远程更新并变基
          git push origin main  # 推送到远程 main 分支
        else
          echo "::error::文件为空或不存在，跳过提交"
          exit 1
        fi