name: CNTV EPG
on:
  schedule:
    - cron: '0 17 * * *'  # 每天UTC 17:00（北京时间凌晨1点）
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install requests lxml pytz

      - name: 运行EPG抓取脚本
        run: |
          # 强制删除旧文件以确保重新生成
          rm -f cntvepg.xml.gz
          python cntvepg/cntvepg.py

      - name: 配置Git用户
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 检查文件变更
        id: check-changes
        run: |
          git add cntvepg.xml.gz
          if git diff --staged --quiet; then
            echo "::notice::无实际内容变更"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "::notice::检测到EPG内容更新"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 提交并推送变更
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git commit -m "自动更新CNTVEPG数据 [$(date +'%Y-%m-%d %H:%M')]"
          git push
